#!/bin/bash
docker pull docker.io/tonistiigi/binfmt:latest
docker image inspect docker.io/tonistiigi/binfmt:latest
docker run --rm --privileged docker.io/tonistiigi/binfmt:latest --install all
docker run --rm --privileged docker.io/tonistiigi/binfmt:latest
docker buildx ls